# Generated by Django 4.2.6 on 2024-01-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sname', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('sage', models.IntegerField()),
                ('smobile', models.CharField(max_length=10)),
            ],
        ),
    ]
